from pathlib import Path
import re


def rd(p): return Path(p).read_text(encoding='utf-8')
def wr(p,s): Path(p).write_text(s,encoding='utf-8'); print('updated',p)
def rep(s,a,b,label):
    if a not in s: raise RuntimeError('missing '+label)
    return s.replace(a,b,1)
def sub(s,p,r,label):
    s,n=re.subn(p,r,s,count=1,flags=re.S)
    if n!=1: raise RuntimeError(f'{label}: {n}')
    return s

# 1) Make /nos-soins/ an unmistakable treatment hub, distinct from routine care.
p='nos-soins/index.html'; s=rd(p)
for a,b,l in [
('<title>Nos soins dentaires à Tanger | Centre Dentaire Venezuela</title>','<title>Traitements dentaires à Tanger | Centre Dentaire Venezuela</title>','hub title'),
('content="Découvrez les soins dentaires proposés à Tanger au Centre Dentaire Venezuela : soins généraux, chirurgie, esthétique, implants, endodontie, parodontologie et orthodontie."','content="Découvrez les traitements et spécialités dentaires proposés à Tanger : soins généraux, chirurgie, esthétique, implants, endodontie, parodontologie et orthodontie."','hub meta'),
('content="Nos soins dentaires à Tanger | Centre Dentaire Venezuela"','content="Traitements dentaires à Tanger | Centre Dentaire Venezuela"','hub og'),
('content="Les principales prises en charge dentaires proposées au Centre Dentaire Venezuela à Tanger."','content="Vue d’ensemble des traitements et spécialités dentaires proposés au Centre Dentaire Venezuela à Tanger."','hub og desc'),
('"name":"Nos soins dentaires à Tanger"','"name":"Nos traitements et spécialités dentaires à Tanger"','hub schema page'),
('"name":"Soins dentaires à Tanger"','"name":"Traitements et spécialités dentaires à Tanger"','hub schema list'),
('<h1>Nos soins dentaires à Tanger</h1>','<h1>Nos traitements et spécialités dentaires à Tanger</h1>','hub h1'),
('<p>Une vue claire des principales prises en charge proposées au cabinet. Chaque page détaille les motifs de consultation, le déroulement, les limites et les questions fréquentes liées au soin.</p>','<p>Cette page sert de guide vers les différentes familles de traitements proposées au cabinet. Pour les soins courants comme le détartrage, les caries et les obturations, consultez la page dédiée aux soins dentaires ; pour les traitements spécialisés, choisissez directement la spécialité concernée.</p>','hub intro'),
('<h2>Choisir une prise en charge</h2>','<h2>Explorer nos traitements par spécialité</h2>','hub h2'),
('<p class="lead">Le traitement adapté dépend toujours d’un examen clinique. Ces pages permettent de mieux comprendre les grandes familles de soins avant votre rendez-vous.</p>','<p class="lead">Le traitement adapté dépend toujours d’un examen clinique. Ce hub organise les soins par intention et oriente vers une page dédiée pour chaque famille de traitement.</p>','hub lead')]: s=rep(s,a,b,l)
wr(p,s)

# 2) Keep the whitening service page commercial/transactional and remove duplicated FAQ/source blocks.
p='blanchiment-dentaire-tanger/index.html'; s=rd(p)
a='<section class="section"><div class="inner"><div class="section-head"><span class="kicker">Résultat</span><h2>Combien de temps le résultat peut-il durer ?</h2><p class="lead">Le blanchiment n’est pas permanent. La couleur évolue à nouveau avec le temps, notamment sous l’effet du café, du thé, du tabac et de certaines habitudes alimentaires.</p></div><div class="facts-grid"><div class="fact-card"><h3>Entretien</h3><p>Une bonne hygiène, des contrôles réguliers et des habitudes limitant les colorants contribuent à maintenir le résultat plus longtemps.</p></div><div class="fact-card"><h3>Retouches</h3><p>Selon le protocole utilisé et l’évolution de la teinte, une retouche peut parfois être proposée plutôt que de recommencer un traitement complet.</p></div><div class="fact-card"><h3>Résultat naturel</h3><p>Le but n’est pas d’obtenir un blanc artificiel, mais une teinte plus lumineuse compatible avec vos dents et les restaurations visibles.</p></div></div></div></section>'
b='<section class="section"><div class="inner"><div class="section-head"><span class="kicker">Résultat</span><h2>Combien de temps le résultat peut-il durer ?</h2><p class="lead">Le blanchiment n’est pas permanent. La tenue du résultat varie selon la teinte initiale, le protocole, l’hygiène et l’exposition au café, au thé, au tabac ou à d’autres colorants.</p></div><p>Des retouches peuvent parfois être envisagées après contrôle plutôt que de recommencer systématiquement un traitement complet. Pour approfondir l’efficacité, la sensibilité et l’entretien, consultez notre <a href="/blog/blanchiment-dentaire-guide/">guide avant un blanchiment dentaire</a>.</p></div></section>'
s=rep(s,a,b,'duration section')
a='<section class="section alt"><div class="inner"><div class="section-head"><span class="kicker">Sensibilité et sécurité</span><h2>Le blanchiment dentaire abîme-t-il les dents ?</h2><p class="lead">Lorsqu’ils sont correctement utilisés, les produits à base de peroxyde disposent d’un recul important en dentisterie. L’effet indésirable le plus fréquent reste la sensibilité dentaire temporaire, parfois accompagnée d’une irritation gingivale transitoire.</p></div><div class="content-grid"><div><p>La sensibilité peut varier selon la concentration du produit, la technique, la durée d’exposition et la sensibilité initiale. C’est une des raisons pour lesquelles un protocole professionnel doit être individualisé plutôt que choisi uniquement en fonction de la puissance annoncée du produit ou de la présence d’une lampe.</p><p>Les revues scientifiques récentes ne montrent pas qu’une activation lumineuse ou laser améliore systématiquement le résultat final. Le produit, sa concentration, le temps d’application, la protection des tissus et la sélection du patient comptent davantage dans la planification du traitement.</p></div><aside class="note"><b>Ce que nous évitons</b><p>Promettre un nombre exact de teintes, un résultat identique pour tous ou présenter une lampe comme une garantie de résultat. La réponse dépend de la teinte initiale et de la nature des colorations.</p></aside></div></div></section>'
b='<section class="section alt"><div class="inner"><div class="section-head"><span class="kicker">Sensibilité et sécurité</span><h2>Le blanchiment dentaire abîme-t-il les dents ?</h2><p class="lead">L’effet indésirable le plus fréquent est une sensibilité temporaire. Le risque dépend notamment du protocole, de la concentration, de la durée d’exposition et de la sensibilité initiale.</p></div><div class="content-grid"><div><p>Le traitement doit donc être choisi après examen plutôt qu’en fonction de la seule puissance annoncée d’un produit ou d’une lampe. Notre article <a href="/blog/blanchiment-dentaire-guide/">« Avant un blanchiment dentaire : 7 choses à savoir »</a> détaille les données récentes sur la sensibilité, les concentrations de peroxyde et l’activation lumineuse.</p></div><aside class="note"><b>Ce que nous évitons</b><p>Promettre un nombre exact de teintes, un résultat identique pour tous ou présenter une lampe comme une garantie de résultat.</p></aside></div></div></section>'
s=rep(s,a,b,'safety section')
faq='''<section class="section alt"><div class="inner"><div class="section-head"><span class="kicker">Questions fréquentes</span><h2>Blanchiment dentaire à Tanger : les réponses utiles</h2></div><div class="faq"><details><summary>Est-ce qu’un détartrage est toujours nécessaire avant ?</summary><p>Non. Il peut être conseillé si du tartre ou des dépôts gênent l’évaluation de la teinte ou risquent de rendre l’éclaircissement moins homogène.</p></details><details><summary>Le blanchiment fonctionne-t-il sur une couronne ou une facette ?</summary><p>Non. Le gel agit sur les tissus dentaires naturels, pas sur une couronne, une facette, un composite ou un implant.</p></details><details><summary>Peut-on avoir mal après un blanchiment ?</summary><p>Une sensibilité transitoire peut apparaître. Son intensité dépend du patient et du protocole.</p></details><details><summary>Combien de séances faut-il ?</summary><p>Il n’existe pas de nombre universel. La teinte de départ, le type de coloration, la méthode et l’objectif déterminent le protocole.</p></details><details><summary>Combien de temps dure le résultat ?</summary><p>La tenue varie selon le protocole, l’hygiène et les habitudes comme le café, le thé ou le tabac. Une retouche peut parfois être discutée après contrôle.</p></details><details><summary>La lampe LED ou le laser rendent-ils forcément le blanchiment plus efficace ?</summary><p>Non. Les données disponibles ne montrent pas un bénéfice final constant de l’activation lumineuse. Le diagnostic, le gel, le temps d’application et la protection des tissus restent déterminants.</p></details><details><summary>Que faut-il éviter après la séance ?</summary><p>Les consignes sont adaptées au protocole. Limiter temporairement les boissons et aliments très colorants ainsi que le tabac peut aider à préserver la teinte obtenue.</p></details><details><summary>Quel est le prix d’un blanchiment dentaire à Tanger ?</summary><p>Le coût dépend de la méthode, du nombre de séances, des éventuels soins préalables et du suivi. Le cabinet confirme le protocole et le devis après examen.</p></details></div></div></section>'''
s=sub(s,r'<section class="section alt"><div class="inner"><div class="section-head"><span class="kicker">Questions fréquentes</span><h2>Blanchiment dentaire à Tanger : les réponses utiles</h2></div><div class="faq">.*?</div></div></section>',faq,'main FAQ')
s=sub(s,r'\n<section class="section" aria-labelledby="faq-prix-blanchiment-title">.*?</section>\n','\n','duplicate FAQ')
s=sub(s,r'\n<section class="section alt"><div class="inner"><div class="section-head"><span class="kicker">Références</span><h2>Sources médicales utilisées</h2></div><p class="sources">.*?</p></div></section>\n','\n','duplicate sources')
wr(p,s)

# 3) Make the brand-comparison article informational instead of a second local landing page.
p='blog/flash-opalescence-philips-zoom-blanchiment/index.html'; s=rd(p)
for a,b,l in [
('<title>Blanchiment Zoom, fläsh ou Opalescence à Tanger : comparatif</title>','<title>Philips Zoom, fläsh ou Opalescence : comparatif | Tanger</title>','cmp title'),
('content="Blanchiment Zoom, fläsh ou Opalescence à Tanger : quelles différences ?"','content="Philips Zoom, fläsh ou Opalescence : quelles différences ?"','cmp og'),
('<h1>Blanchiment Zoom, fläsh ou Opalescence à Tanger : quelles différences ?</h1>','<h1>Philips Zoom, fläsh ou Opalescence : quelles différences ?</h1>','cmp h1'),
('<h2>1. Blanchiment fläsh à Tanger : que dit le fabricant ?</h2>','<h2>1. Blanchiment fläsh : que dit le fabricant ?</h2>','cmp flash'),
('<h2>2. Blanchiment Opalescence à Tanger : gouttières professionnelles supervisées</h2>','<h2>2. Blanchiment Opalescence : gouttières professionnelles supervisées</h2>','cmp opa')]: s=rep(s,a,b,l)
s=sub(s,r'<p class="lead">Vous recherchez un <strong>blanchiment dentaire Zoom à Tanger</strong>, un <strong>blanchiment fläsh à Tanger</strong> ou un protocole <strong>Opalescence à Tanger</strong> \? Ces marques ne correspondent pas au même type de traitement\. Ce guide compare leurs protocoles à partir des sites officiels fläsh, Opalescence et Philips, puis explique les points à vérifier avec votre dentiste avant de choisir\.</p>','<p class="lead">Philips Zoom WhiteSpeed, fläsh et Opalescence correspondent à des protocoles professionnels différents. Ce guide compare leurs principes à partir des informations officielles des fabricants et explique les points à vérifier avec votre dentiste avant de choisir. Pour une prise en charge locale, consultez notre page <a href="/blanchiment-dentaire-tanger/"><strong>blanchiment dentaire à Tanger</strong></a>.</p>','cmp lead')
anchor='</p><h2>1. Blanchiment fläsh : que dit le fabricant ?</h2>'
s=rep(s,anchor,'</p><p>Pour les données cliniques sur l’efficacité, la sensibilité, le peroxyde et les lampes, consultez aussi <a href="/blog/blanchiment-dentaire-guide/"><strong>notre guide sur les 7 points à connaître avant un blanchiment</strong></a>.</p><h2>1. Blanchiment fläsh : que dit le fabricant ?</h2>','cmp crosslink')
s=s.replace('<div class="meta">Publié le 12 septembre 2026</div>','<div class="meta">Publié le 12 septembre 2026 · Mis à jour le 13 septembre 2026</div>',1)
wr(p,s)

# 4) Complete the whitening-cluster triangle with a contextual article-to-article link.
p='blog/blanchiment-dentaire-guide/index.html'; s=rd(p)
s=s.replace('Publié le 9 septembre 2026 · Mis à jour le 11 septembre 2026','Publié le 9 septembre 2026 · Mis à jour le 13 septembre 2026',1)
t='<p class="evidence">Revue parapluie 2026 : <a href="https://pubmed.ncbi.nlm.nih.gov/42076873/" target="_blank" rel="noopener noreferrer">PubMed PMID 42076873</a>. Étude pilote, juillet 2026 : <a href="https://pubmed.ncbi.nlm.nih.gov/42469727/" target="_blank" rel="noopener noreferrer">PubMed PMID 42469727</a>.</p>'
s=rep(s,t,t+'<p>Pour comparer les systèmes commerciaux qui utilisent des protocoles différents, consultez notre <a href="/blog/flash-opalescence-philips-zoom-blanchiment/"><strong>comparatif Philips Zoom, fläsh et Opalescence</strong></a>.</p>','guide crosslink')
wr(p,s)

# 5) Persist the architecture rule for future content.
p='.github/project-docs/seo-content-rules.md'; s=rd(p)
if '## Architecture des clusters et intention de recherche' not in s:
    s=s.rstrip()+'''\n\n## Architecture des clusters et intention de recherche\n\n- Une page soin locale reste la page commerciale/transactionnelle principale pour son service.\n- Les articles ciblent des intentions informationnelles distinctes et renvoient vers la page soin correspondante.\n- Quand un article dédié existe, la page soin répond brièvement puis renvoie vers lui au lieu de dupliquer toute la réponse.\n- Éviter plusieurs pages visant exactement la même combinaison service + ville.\n- `/nos-soins/` est le hub des traitements et spécialités ; `/soins-dentaires-tanger/` cible les soins courants.\n- Les articles d’un même cluster peuvent se lier entre eux lorsque le lien est naturel, puis tous renvoient vers la page soin mère.\n- Les entités structurées utilisent les IDs canoniques `/#website`, `/#dentist` et `/dr-majda-laasraoui-dentiste-tanger/#person`.\n'''
    wr(p,s+'\n')
