from pathlib import Path
import json, re

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / 'blog/blanchiment-dentaire-avant-mariage/index.html'
html = path.read_text()

old_citations = '"citation":["https://www.brides.com/story/wedding-teeth-whitening-ideas","https://pubmed.ncbi.nlm.nih.gov/38371984/","https://pubmed.ncbi.nlm.nih.gov/41896506/","https://pubmed.ncbi.nlm.nih.gov/42501317/","https://pubmed.ncbi.nlm.nih.gov/42076873/"]'
new_citations = '"citation":["https://www.brides.com/story/wedding-teeth-whitening-ideas","https://pubmed.ncbi.nlm.nih.gov/40485133/","https://pubmed.ncbi.nlm.nih.gov/41896506/","https://pubmed.ncbi.nlm.nih.gov/42501317/","https://pubmed.ncbi.nlm.nih.gov/42076873/","https://pubmed.ncbi.nlm.nih.gov/40484311/","https://pubmed.ncbi.nlm.nih.gov/38668030/","https://pubmed.ncbi.nlm.nih.gov/39078468/"]'
assert old_citations in html
html = html.replace(old_citations, new_citations, 1)

old_summary = '<div class="callout blog-summary"><b>En bref</b><p>Évitez de commencer un blanchiment dentaire à la dernière minute avant un mariage. Le magazine Brides conseille d’anticiper et indique qu’un processus de blanchiment peut prendre une à deux semaines selon l’objectif. Côté médical, les études montrent que la sensibilité est un effet indésirable fréquent et qu’elle est surtout surveillée dans les premières 24 à 48 heures. Le planning doit donc être individualisé après examen.</p></div>'
new_summary = '<div class="callout blog-summary"><b>En bref</b><p>Pour un mariage, l’idée importante est d’éviter de découvrir un nouveau protocole au dernier moment. Brides sert ici uniquement de repère éditorial “wedding” pour l’anticipation. Le calendrier médical repose surtout sur les données PubMed : les techniques au cabinet et à domicile supervisé peuvent toutes deux être efficaces, la sensibilité varie selon les protocoles et les concentrations, et les premières 24 à 48 heures sont une période particulièrement utile à surveiller après certains blanchiments au fauteuil. Le planning doit donc être individualisé après examen.</p></div>'
assert old_summary in html
html = html.replace(old_summary, new_summary, 1)

old_timing = '<p>Il n’existe pas un délai universel. Pour un mariage, l’objectif est surtout de <strong>ne pas coller le traitement au jour J</strong>. Dans son guide consacré au sourire avant mariage, <a href="https://www.brides.com/story/wedding-teeth-whitening-ideas" target="_blank" rel="noopener noreferrer">Brides recommande de commencer suffisamment tôt</a> et indique que le processus peut prendre au moins une à deux semaines selon le résultat recherché. Ce repère relève d’un conseil éditorial mariage, pas d’une règle médicale.</p>'
new_timing = '<p>Il n’existe pas un délai médical universel du type “X jours avant le mariage”. Pour un mariage, l’objectif est surtout de <strong>ne pas coller le traitement au jour J</strong>. Dans son guide consacré au sourire avant mariage, <a href="https://www.brides.com/story/wedding-teeth-whitening-ideas" target="_blank" rel="noopener noreferrer">Brides recommande d’anticiper</a>. Nous utilisons cette source uniquement pour le contexte mariage ; le choix du protocole et du délai repose sur l’examen clinique et les données scientifiques.</p>'
assert old_timing in html
html = html.replace(old_timing, new_timing, 1)

old_second = '<p>En pratique, le calendrier dépend du protocole, de la teinte de départ, de la présence de restaurations, de l’état des gencives et d’une éventuelle sensibilité. Au Centre Dentaire Venezuela, le planning est défini après examen par <a href="/dr-majda-laasraoui-dentiste-tanger/">Dr Majda Laasraoui</a>. Si vous souhaitez organiser le traitement à Tanger, la page <a href="/blanchiment-dentaire-tanger/"><strong>blanchiment dentaire professionnel à Tanger</strong></a> détaille le déroulement et les options.</p>'
new_second = old_second + '<p class="evidence">Une <a href="https://pubmed.ncbi.nlm.nih.gov/40485133/" target="_blank" rel="noopener noreferrer">revue systématique et méta-analyse mise à jour en 2025</a> a comparé les techniques au cabinet et à domicile supervisé : les deux peuvent obtenir un éclaircissement, avec des différences de sensibilité et de mesure de couleur selon les protocoles. Cela confirme qu’un planning de mariage doit être choisi selon le cas, et non uniquement selon la promesse de rapidité.</p>'
assert old_second in html
html = html.replace(old_second, new_second, 1)

pattern = re.compile(r'<h2>Ce que les études disent vraiment avant de choisir son planning</h2>.*?<p class="evidence">Sources : .*?</p>', re.S)
new_evidence_block = '''<h2>Ce que les études disent vraiment avant de choisir son planning</h2>
<div class="table-wrap"><table class="geo-table"><thead><tr><th>Question</th><th>Résultat scientifique</th><th>Ce que cela change avant un mariage</th></tr></thead><tbody><tr><td><strong>Cabinet ou domicile supervisé ?</strong></td><td>Une revue systématique et méta-analyse mise à jour en 2025 a inclus 32 études qualitatives et 23 dans la méta-analyse. Elle n’a pas trouvé de différence significative sur le risque de sensibilité ni sur le changement de teinte mesuré par guide ; l’intensité de sensibilité était plus faible à domicile, avec une qualité de preuve jugée faible.</td><td>Le protocole “le plus rapide” n’est pas automatiquement le meilleur choix avant un mariage. Le temps disponible, la sensibilité et l’adhésion au traitement comptent.</td></tr><tr><td><strong>La concentration influence-t-elle la sensibilité ?</strong></td><td>Une umbrella review 2026 conclut que des concentrations faibles à modérées au fauteuil peuvent donner un éclaircissement comparable aux concentrations plus élevées tout en réduisant la sensibilité. Une network meta-analysis 2025 retrouve aussi davantage de sensibilité avec certaines concentrations élevées à domicile.</td><td>Choisir uniquement le produit le plus concentré pour gagner du temps avant le jour J n’est pas une stratégie fondée sur les meilleures données.</td></tr><tr><td><strong>LED ou laser = plus blanc ?</strong></td><td>Une umbrella review 2026 n’a pas retrouvé de bénéfice final constant de l’activation par lumière ou laser sur l’efficacité du blanchiment.</td><td>Une promesse “express grâce à la lampe” ne doit pas, à elle seule, déterminer la date ou la méthode avant le mariage.</td></tr><tr><td><strong>Faut-il suivre un “régime blanc” strict ?</strong></td><td>Une revue systématique et méta-analyse 2024 n’a pas montré d’amélioration significative du résultat avec des restrictions alimentaires strictes pendant ou après le blanchiment.</td><td>Avant le mariage, mieux vaut suivre les consignes personnalisées du dentiste plutôt que s’imposer automatiquement un régime blanc très restrictif.</td></tr><tr><td><strong>Peut-on réduire la sensibilité ?</strong></td><td>Une revue systématique 2024 rapporte que certains dentifrices désensibilisants peuvent réduire la sensibilité après certains protocoles de blanchiment.</td><td>Chez une personne sensible ou avec une date de mariage proche, la prévention de la sensibilité peut faire partie du plan discuté avec le dentiste.</td></tr></tbody></table></div>
<p class="evidence">Sources PubMed : <a href="https://pubmed.ncbi.nlm.nih.gov/40485133/" target="_blank" rel="noopener noreferrer">méta-analyse 2025 cabinet vs domicile</a>, <a href="https://pubmed.ncbi.nlm.nih.gov/41896506/" target="_blank" rel="noopener noreferrer">umbrella review 2026 sur les protocoles au fauteuil</a>, <a href="https://pubmed.ncbi.nlm.nih.gov/40484311/" target="_blank" rel="noopener noreferrer">network meta-analysis 2025 sur la sensibilité à domicile</a>, <a href="https://pubmed.ncbi.nlm.nih.gov/42076873/" target="_blank" rel="noopener noreferrer">umbrella review 2026 sur l’activation lumineuse</a>, <a href="https://pubmed.ncbi.nlm.nih.gov/38668030/" target="_blank" rel="noopener noreferrer">revue systématique et méta-analyse 2024 sur le “régime blanc”</a> et <a href="https://pubmed.ncbi.nlm.nih.gov/39078468/" target="_blank" rel="noopener noreferrer">revue systématique 2024 sur les dentifrices désensibilisants</a>.</p>'''
html, n = pattern.subn(new_evidence_block, html, count=1)
assert n == 1

old_det = '<p>Le détartrage n’est pas une étape obligatoire avant chaque blanchiment. Il devient pertinent s’il existe du tartre ou des dépôts qui gênent l’évaluation de la teinte ou l’hygiène. Brides conseille aussi de prévoir un nettoyage professionnel dans la préparation du sourire avant mariage. Là encore, ce conseil doit être adapté à la situation clinique.</p>'
new_det = '<p>Le détartrage n’est pas une étape obligatoire avant chaque blanchiment. Il devient pertinent s’il existe du tartre ou des dépôts qui gênent l’évaluation de la teinte, l’hygiène ou l’examen clinique. La décision doit donc venir du bilan dentaire, et non d’une checklist mariage générique.</p>'
assert old_det in html
html = html.replace(old_det, new_det, 1)

old_keep = '<p>Après le traitement, l’objectif est surtout de ne pas multiplier les changements de dernière minute. Conservez une hygiène régulière, suivez les consignes données après votre séance et limitez les habitudes qui favorisent les colorations, notamment le tabac et la consommation fréquente de boissons très pigmentées. Brides insiste également sur l’entretien quotidien du sourire pendant les semaines précédant le mariage.</p>'
new_keep = '<p>Après le traitement, l’objectif est surtout de garder une routine stable et de suivre les consignes données pour votre protocole. Il n’est pas nécessaire d’imposer automatiquement un “régime blanc” strict : une <a href="https://pubmed.ncbi.nlm.nih.gov/38668030/" target="_blank" rel="noopener noreferrer">revue systématique et méta-analyse publiée en 2024</a> n’a pas montré d’amélioration significative du résultat du blanchiment avec des restrictions alimentaires strictes pendant ou après le traitement. L’hygiène habituelle et les recommandations individualisées du dentiste restent prioritaires.</p>'
assert old_keep in html
html = html.replace(old_keep, new_keep, 1)

old_faq = 'Une bonne hygiène et la limitation des habitudes qui favorisent les colorations, comme le tabac ou la consommation fréquente de boissons très pigmentées, peuvent aider à préserver la teinte obtenue.'
new_faq = 'Une bonne hygiène et les consignes adaptées au protocole restent prioritaires. Une revue systématique et méta-analyse 2024 n’a pas montré de bénéfice significatif d’un “régime blanc” strict sur le résultat du blanchiment.'
assert html.count(old_faq) >= 2
html = html.replace(old_faq, new_faq)

sources_pattern = re.compile(r'<section class="sources" aria-labelledby="sources-title">.*?</section>', re.S)
new_sources = '''<section class="sources" aria-labelledby="sources-title"><h2 id="sources-title">Sources utilisées</h2><p><strong>Contexte mariage</strong></p><ul><li><a href="https://www.brides.com/story/wedding-teeth-whitening-ideas" target="_blank" rel="noopener noreferrer">Brides — guide éditorial sur la préparation du sourire avant le mariage.</a></li></ul><p><strong>Sources scientifiques PubMed</strong></p><ul><li><a href="https://pubmed.ncbi.nlm.nih.gov/40485133/" target="_blank" rel="noopener noreferrer">de Geus JL et al. At-home vs In-office Bleaching: An Updated Systematic Review and Meta-analysis. Operative Dentistry, 2025.</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/41896506/" target="_blank" rel="noopener noreferrer">Hajeer O, Hasan A. In-office tooth bleaching protocols: umbrella review of systematic reviews and meta-analyses, 2026.</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/40484311/" target="_blank" rel="noopener noreferrer">Terra RMO et al. Effect of at-home bleaching agents and concentrations on tooth sensitivity: systematic review and network meta-analysis, 2025.</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/42501317/" target="_blank" rel="noopener noreferrer">Gok A, Koprucuogullari B. Randomized clinical trial on short-term color stability and tooth sensitivity after in-office bleaching, 2026.</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/42076873/" target="_blank" rel="noopener noreferrer">Basualdo Allende J et al. Laser and light activation in office bleaching: umbrella review, 2026.</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/38668030/" target="_blank" rel="noopener noreferrer">Is a White Diet Necessary for Tooth Bleaching Procedures? Systematic Review and Meta-analysis, 2024.</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/39078468/" target="_blank" rel="noopener noreferrer">Effectiveness of desensitizing toothpastes in reducing tooth sensitivity after tooth bleaching: systematic review, 2024.</a></li></ul><p class="evidence">Les sources mariage servent uniquement à contextualiser la préparation du jour J. Les affirmations sur l’efficacité, la sensibilité, les concentrations, la lumière et les restrictions alimentaires reposent sur les publications scientifiques ci-dessus.</p></section>'''
html, n = sources_pattern.subn(new_sources, html, count=1)
assert n == 1

# Validate structured data and evidence/source expectations
for block in re.findall(r'<script type="application/ld\+json">(.*?)</script>', html, flags=re.S):
    json.loads(block)
assert html.count('www.brides.com/story/wedding-teeth-whitening-ideas') >= 2
for pmid in ['40485133','41896506','40484311','42501317','42076873','38668030','39078468']:
    assert pmid in html, pmid
assert '38371984' not in html
assert 'régime blanc' in html.lower()

path.write_text(html)
print('Wedding whitening article upgraded to PubMed-first evidence.')
